### ISSUE TITLE
move refs and remove JN

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/chillingconcepts#8]
@ngoj1 Can you move the refs folder you have to [here](https://github.com/lizzieinvancouver/chillingconcepts/tree/main/refs) and call it something clearer like: refsReviewedJNgo or such? Thank you!

**Comment by ngoj1** [comment]
Done! I also moved the Zotero exported reference list over to the same folder.

**Comment by lizzieinvancouver** [comment]
Thank you!
